# Generated by Django 2.2.12 on 2020-04-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weltladen', '0004_locations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weltladenproduct',
            options={'ordering': ['order'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='weltladenproduct',
            name='storage',
        ),
    ]
