# Generated by Django 2.2.12 on 2020-04-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weltladen', '0004_auto_20200405_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrytranslation',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='countrytranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
