# Generated by Django 2.2.12 on 2020-04-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weltladen', '0005_auto_20200407_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=12, verbose_name='ZIP / Postal code')),
                ('city', models.CharField(max_length=1024, verbose_name='City')),
                ('country', models.CharField(max_length=25, verbose_name='Country')),
                ('distance', models.PositiveIntegerField(verbose_name='Distance to Baden')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
