# Generated by Django 2.2.12 on 2020-05-01 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import shop.money.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('weltladen', '0005_auto_20200426_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='weltladenproduct',
            name='additional_manufacturers',
            field=models.ManyToManyField(related_name='additional_manufacturers', to='weltladen.Manufacturer', verbose_name='Additional Manufacturers'),
        ),
        migrations.AddField(
            model_name='weltladenproduct',
            name='fairtrade',
            field=models.BooleanField(default=True, verbose_name='Fairtrade'),
        ),
        migrations.AddField(
            model_name='weltladenproduct',
            name='gluten_free',
            field=models.BooleanField(default=False, verbose_name='Gluten free'),
        ),
        migrations.AddField(
            model_name='weltladenproduct',
            name='lactose_free',
            field=models.BooleanField(default=False, verbose_name='Lactose free'),
        ),
        migrations.AlterField(
            model_name='weltladencustomer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weltladenproduct',
            name='unit_price',
            field=shop.money.fields.MoneyField(decimal_places=3, help_text='Gross price for this product', verbose_name='Unit price'),
        ),
        migrations.CreateModel(
            name='BioQualityLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Bio Quality Label')),
                ('logo', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
    ]
