# Generated by Django 2.2.12 on 2020-05-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weltladen', '0006_auto_20200501_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='weltladenproduct',
            name='bio_quality_label',
            field=models.ForeignKey(default=2, on_delete='Bio Quality Label', to='weltladen.BioQualityLabel'),
            preserve_default=False,
        ),
    ]
