# Generated by Django 2.2.12 on 2020-04-13 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import shop.models.fields

def move_data(apps, schema_editor):
    Customer = apps.get_model('weltladen', 'Customer')
    WeltladenCustomer = apps.get_model('weltladen', 'WeltladenCustomer')
    for customer in Customer.objects.all():
        wc = WeltladenCustomer.objects.create(
            user=customer.user,
            recognized=customer.recognized,
            last_access=customer.last_access,
            extra=customer.extra,
            number=customer.number,
            salutation=customer.salutation
        )
        wc.save()

class Migration(migrations.Migration):

    dependencies = [
        ('email_auth', '0005_auto_20191123_2051'),
        ('weltladen', '0007_auto_20200411_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeltladenCustomer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('recognized', shop.models.fields.ChoiceEnumField(help_text='Designates the state the customer is recognized as.', verbose_name='Recognized as')),
                ('last_access', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last accessed')),
                ('extra', shop.models.fields.JSONField(editable=False, verbose_name='Extra information about this customer')),
                ('number', models.PositiveIntegerField(default=None, null=True, unique=True, verbose_name='Customer Number')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone number')),
                ('salutation', models.CharField(choices=[('mrs', 'Mrs.'), ('mr', 'Mr.'), ('na', '(n/a)')], max_length=5, verbose_name='Salutation')),
            ],
        ),
        migrations.RunPython(move_data),
        migrations.AlterField(
            model_name='billingaddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weltladen.WeltladenCustomer'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='weltladen.WeltladenCustomer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='weltladen.WeltladenCustomer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weltladen.WeltladenCustomer'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
