# Generated by Django 2.2.12 on 2020-05-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weltladen', '0007_weltladenproduct_bio_quality_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weltladenproduct',
            name='additional_manufacturers',
            field=models.ManyToManyField(blank=True, related_name='additional_manufacturers', to='weltladen.Manufacturer', verbose_name='Additional Manufacturers'),
        ),
    ]
