# Generated by Django 2.2.12 on 2020-05-06 14:24

from django.db import migrations, models
import django.db.models.deletion
import shop.models.address


class Migration(migrations.Migration):

    dependencies = [
        ('weltladen', '0008_auto_20200502_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weltladenproduct',
            name='bio_quality_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to='weltladen.BioQualityLabel'),
        ),
        migrations.AlterField(
            model_name='weltladenproduct',
            name='country_of_origin',
            field=shop.models.address.CountryField(blank=True, null=True, verbose_name='Country of origin'),
        ),
        migrations.AlterField(
            model_name='weltladenproduct',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weltladen.Manufacturer', verbose_name='Manufacturer'),
        ),
    ]
