# Generated by Django 2.2.12 on 2020-04-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weltladen', '0008_auto_20200413_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_switch',
            field=models.BooleanField(default=True, help_text='If switched on, then 20% tax item, if off then 10% tax item', verbose_name='Switch Tax'),
        ),
    ]
