# Generated by Django 2.2.12 on 2020-05-17 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weltladen', '0012_auto_20200517_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weltladenproduct',
            name='country_of_origin',
        ),
    ]
