# Generated by Django 3.0.7 on 2020-06-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weltladen', '0013_remove_weltladenproduct_country_of_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='zip_code',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zip_code',
            new_name='postal_code',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address2',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='address',
            field=models.CharField(default=1, max_length=1024, verbose_name='Address line'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='company_name',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Company name'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='house_number',
            field=models.CharField(default=3, max_length=12, verbose_name='House number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(default='Hintschiggasse', max_length=1024, verbose_name='Address line'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='company_name',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Company name'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='house_number',
            field=models.CharField(default=3, max_length=12, verbose_name='House number'),
            preserve_default=False,
        ),
    ]
