# Generated by Django 3.0.8 on 2020-08-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weltladen', '0014_auto_20200630_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='weltladenproduct',
            name='quality_labels',
            field=models.ManyToManyField(blank=True, related_name='quality_labels', to='weltladen.BioQualityLabel', verbose_name='Quality labels'),
        ),
    ]
