# Generated by Django 3.0.8 on 2020-08-25 18:28

from django.db import migrations, models

def make_many_labels(apps, schema_editor):
    WeltladenProduct = apps.get_model('weltladen', 'WeltladenProduct')
    for product in WeltladenProduct.objects.all():
        if product.bio_quality_label:
            product.quality_labels.add(product.bio_quality_label)

class Migration(migrations.Migration):

    dependencies = [
        ('weltladen', '0015_weltladenproduct_quality_lables'),
    ]

    operations = [
        migrations.RunPython(make_many_labels)
    ]
