# Generated by Django 3.0.8 on 2020-08-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weltladen', '0016_auto_20200825_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weltladenproduct',
            name='bio_quality_label',
        ),
        migrations.AlterField(
            model_name='bioqualitylabel',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Quality Label'),
        ),
    ]
