# Generated by Django 3.0.8 on 2020-08-25 19:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('weltladen', '0017_auto_20200825_2129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BioQualityLabel',
            new_name='QualityLabel',
        ),
    ]
