# Generated by Django 3.0.8 on 2020-08-25 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weltladen', '0018_auto_20200825_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weltladenproduct',
            name='fairtrade',
        ),
    ]
