# Generated by Django 3.0.8 on 2020-08-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weltladen', '0019_remove_weltladenproduct_fairtrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitylabel',
            name='ordering',
            field=models.PositiveIntegerField(default=10, verbose_name='Ordering'),
        ),
    ]
