# Generated by Django 3.0.10 on 2020-10-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weltladen', '0022_auto_20201031_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='weltladenproduct',
            name='display_manufacturer_as_raw_material_supplier',
            field=models.BooleanField(default=False, verbose_name='Display manufacturer as raw material supplier'),
        ),
    ]
