# Generated by Django 3.0.11 on 2021-01-24 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weltladen', '0023_weltladenproduct_display_manufacturer_as_raw_material_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='activation_key_expires',
            field=models.DateField(default=datetime.date(2021, 1, 27), verbose_name='Activation Key Expiration'),
        ),
    ]
