# Generated by Django 3.0.11 on 2021-03-11 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weltladen', '0025_auto_20210124_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='weltladenproduct',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Weight in kilograms (kg). max 99.99kg', max_digits=4, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='activation',
            name='activation_key_expires',
            field=models.DateField(default=datetime.date(2021, 3, 14), verbose_name='Activation Key Expiration'),
        ),
    ]
