# Generated by Django 3.0.14 on 2021-11-01 20:04

from django.db import migrations, models
import weltladen.models


class Migration(migrations.Migration):

    dependencies = [
        ('weltladen', '0026_auto_20210311_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='activation_key_expires',
            field=models.DateField(default=weltladen.models.get_default_expiration_date, verbose_name='Activation Key Expiration'),
        ),
    ]
